name: Build the translation pack
on:
  push:
    paths:
      - "pack/**"
      - ".github/workflows/build.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Zip the translation pack
        run: |
          cd pack
          zip -r ../RAD2-1.16.5-client-zh_TW.zip *
          rm -rf mods
          zip -r ../RAD2-1.16.5-server-zh_TW.zip *
      - name: Upload the translation pack (client)
        uses: actions/upload-artifact@v3
        with:
          name: RAD2-1.16.5-client-zh_TW
          path: RAD2-1.16.5-client-zh_TW.zip
      - name: Upload the translation pack (server)
        uses: actions/upload-artifact@v3
        with:
          name: RAD2-1.16.5-server-zh_TW
          path: RAD2-1.16.5-server-zh_TW.zip          
      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "RAD2-1.16.5-client-zh_TW.zip,RAD2-1.16.5-server-zh_TW.zip"
          tag: v_${{ github.run_number }}
          name: RAD2 翻譯包 v${{ github.run_number }}
          body: "Roguelike Adventures and Dungeons (Roguelike 冒險與地下城 2) 模組包的繁體中文（台灣）翻譯包 | 版本：${{ github.run_number }}"
